# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_poster_name',
            field=models.CharField(default='hellooooo', max_length=200),
            preserve_default=False,
        ),
    ]
